@extends('layouts.app', ['title' => 'Audit Log'])

@section('content')
<div class="between mb"><div><h1>Audit Log</h1><p class="muted">Riwayat aksi penting: login, publish ujian, reset device, reset attempt, import, dan perubahan akun.</p></div></div>
<div class="card data-card">
    <div class="table-toolbar"><div class="table-title"><h2>Live Table Audit</h2><p class="muted small mb0">{{ $logs->total() }} catatan audit.</p></div><form class="table-tools" method="GET" action="{{ route('audit.index') }}"><div class="tool-field"><label>Event</label><select class="input" name="event" onchange="this.form.submit()"><option value="">Semua</option>@foreach($events as $event)<option value="{{ $event }}" @selected(request('event')===$event)>{{ $event }}</option>@endforeach</select></div><div class="tool-field search"><label>Live Search</label><div class="live-search-wrap"><input class="input" data-live-search="auditTable" name="q" value="{{ request('q') }}" placeholder="Cari event, user, IP"></div></div><button class="btn primary">Cari</button><button class="btn" type="button" data-live-reset="auditTable">Clear</button></form></div>
    <div class="table-wrap"><table class="table" id="auditTable"><thead><tr><th>Waktu</th><th>Event</th><th>User</th><th>Objek</th><th>IP</th><th>Detail</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ $log->created_at->format('d M Y H:i:s') }}</td><td><span class="badge info">{{ $log->event }}</span></td><td>{{ $log->user?->name ?: 'System' }}<br><span class="muted small">{{ $log->user?->email }}</span></td><td>{{ class_basename($log->auditable_type) ?: '-' }} #{{ $log->auditable_id ?: '-' }}</td><td>{{ $log->ip_address ?: '-' }}</td><td><pre class="code" style="max-width:420px">{{ json_encode($log->properties, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></td></tr>@empty<tr data-empty-row><td colspan="6">Belum ada audit log.</td></tr>@endforelse</tbody></table></div>
    <div class="table-meta between"><div class="small muted">Terlihat: <b data-live-count="auditTable">{{ $logs->count() }}</b> baris</div><div>{{ $logs->links() }}</div></div>
</div>
@endsection
